export interface DDD {
  code: string;
  region: string;
}

export const DDDS: DDD[] = [
  { code: '11', region: 'São Paulo - SP' },
  { code: '12', region: 'São José dos Campos - SP' },
  { code: '13', region: 'Santos - SP' },
  { code: '14', region: 'Bauru - SP' },
  { code: '15', region: 'Sorocaba - SP' },
  { code: '16', region: 'Ribeirão Preto - SP' },
  { code: '17', region: 'São José do Rio Preto - SP' },
  { code: '18', region: 'Presidente Prudente - SP' },
  { code: '19', region: 'Campinas - SP' },
  { code: '21', region: 'Rio de Janeiro - RJ' },
  { code: '22', region: 'Campos dos Goytacazes - RJ' },
  { code: '24', region: 'Volta Redonda - RJ' },
  { code: '27', region: 'Vitória - ES' },
  { code: '28', region: 'Cachoeiro de Itapemirim - ES' },
  { code: '31', region: 'Belo Horizonte - MG' },
  { code: '32', region: 'Juiz de Fora - MG' },
  { code: '33', region: 'Governador Valadares - MG' },
  { code: '34', region: 'Uberlândia - MG' },
  { code: '35', region: 'Poços de Caldas - MG' },
  { code: '37', region: 'Divinópolis - MG' },
  { code: '38', region: 'Montes Claros - MG' },
  { code: '41', region: 'Curitiba - PR' },
  { code: '42', region: 'Ponta Grossa - PR' },
  { code: '43', region: 'Londrina - PR' },
  { code: '44', region: 'Maringá - PR' },
  { code: '45', region: 'Foz do Iguaçu - PR' },
  { code: '46', region: 'Francisco Beltrão - PR' },
  { code: '47', region: 'Joinville - SC' },
  { code: '48', region: 'Florianópolis - SC' },
  { code: '49', region: 'Chapecó - SC' },
  { code: '51', region: 'Porto Alegre - RS' },
  { code: '53', region: 'Pelotas - RS' },
  { code: '54', region: 'Caxias do Sul - RS' },
  { code: '55', region: 'Santa Maria - RS' },
  { code: '61', region: 'Brasília - DF' },
  { code: '62', region: 'Goiânia - GO' },
  { code: '63', region: 'Palmas - TO' },
  { code: '64', region: 'Rio Verde - GO' },
  { code: '65', region: 'Cuiabá - MT' },
  { code: '66', region: 'Rondonópolis - MT' },
  { code: '67', region: 'Campo Grande - MS' },
  { code: '68', region: 'Rio Branco - AC' },
  { code: '69', region: 'Porto Velho - RO' },
  { code: '71', region: 'Salvador - BA' },
  { code: '73', region: 'Ilhéus - BA' },
  { code: '74', region: 'Juazeiro - BA' },
  { code: '75', region: 'Feira de Santana - BA' },
  { code: '77', region: 'Barreiras - BA' },
  { code: '79', region: 'Aracaju - SE' },
  { code: '81', region: 'Recife - PE' },
  { code: '82', region: 'Maceió - AL' },
  { code: '83', region: 'João Pessoa - PB' },
  { code: '84', region: 'Natal - RN' },
  { code: '85', region: 'Fortaleza - CE' },
  { code: '86', region: 'Teresina - PI' },
  { code: '87', region: 'Petrolina - PE' },
  { code: '88', region: 'Juazeiro do Norte - CE' },
  { code: '89', region: 'Picos - PI' },
  { code: '91', region: 'Belém - PA' },
  { code: '92', region: 'Manaus - AM' },
  { code: '93', region: 'Santarém - PA' },
  { code: '94', region: 'Marabá - PA' },
  { code: '95', region: 'Boa Vista - RR' },
  { code: '96', region: 'Macapá - AP' },
  { code: '97', region: 'Coari - AM' },
  { code: '98', region: 'São Luís - MA' },
  { code: '99', region: 'Imperatriz - MA' },
];